### ISSUE TITLE
i have failed jonbs in supervisor in multi proc

### ISSUE THREAD

**Issue by vahidalvandi** [archtechx/jobpipeline#11]
```
nano /etc/supervisor/conf.d/laravel-worker.conf

[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=/var/www/src/artisan queue:work
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
numprocs=4
redirect_stderr=true
stdout_logfile=/var/log/supervisor/laravel-queue.log
stopwaitsecs=3600
```

```
Illuminate\Queue\MaxAttemptsExceededException: Stancl\JobPipeline\JobPipeline has been attempted too many times or run too long. The job may have previously timed out. in /var/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:746
Stack trace:
#0 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(214): Illuminate\Queue\Worker->maxAttemptsExceededException()
#1 /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(545): Illuminate\Queue\Worker->Illuminate\Queue\{closure}()
#2 /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(753): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#3 /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\Database\Connection->runQueryCallback()
#4 /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(546): Illuminate\Database\Connection->run()
#5 /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(498): Illuminate\Database\Connection->statement()
#6 /var/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3224): Illuminate\Database\Connection->insert()
#7 /var/www/vendor/webine/ticketing/src/database/seeders/TicketingTableSeeder.php(487): Illuminate\Database\Query\Builder->insert()
#8 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): webine\ticketing\database\seeders\TicketingTableSeeder->run()
#9 /var/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#10 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#11 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#12 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(663): Illuminate\Container\BoundMethod::call()
#13 /var/www/vendor/laravel/framework/src/Illuminate/Database/Seeder.php(184): Illuminate\Container\Container->call()
#14 /var/www/vendor/laravel/framework/src/Illuminate/Database/Seeder.php(193): Illuminate\Database\Seeder->Illuminate\Database\{closure}()
#15 /var/www/vendor/ranium/laravel-seedonce/src/Traits/SeedOnce.php(45): Illuminate\Database\Seeder->__invoke()
#16 /var/www/vendor/laravel/framework/src/Illuminate/Database/Seeder.php(61): webine\ticketing\database\seeders\TicketingTableSeeder->__invoke()
#17 /var/www/database/seeders/DatabaseSeeder.php(14): Illuminate\Database\Seeder->call()
#18 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Database\Seeders\DatabaseSeeder->run()
#19 /var/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#20 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#21 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#22 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(663): Illuminate\Container\BoundMethod::call()
#23 /var/www/vendor/laravel/framework/src/Illuminate/Database/Seeder.php(184): Illuminate\Container\Container->call()
#24 /var/www/vendor/laravel/framework/src/Illuminate/Database/Seeder.php(193): Illuminate\Database\Seeder->Illuminate\Database\{closure}()
#25 /var/www/vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php(81): Illuminate\Database\Seeder->__invoke()
#26 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/GuardsAttributes.php(155): Illuminate\Database\Console\Seeds\SeedCommand->Illuminate\Database\Console\Seeds\{closure}()
#27 /var/www/vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php(82): Illuminate\Database\Eloquent\Model::unguarded()
#28 /var/www/vendor/stancl/tenancy/src/Commands/Seed.php(59): Illuminate\Database\Console\Seeds\SeedCommand->handle()
#29 /var/www/vendor/stancl/tenancy/src/Tenancy.php(160): Stancl\Tenancy\Commands\Seed->Stancl\Tenancy\Commands\{closure}()
#30 /var/www/vendor/stancl/tenancy/src/Commands/Seed.php(62): Stancl\Tenancy\Tenancy->runForMultiple()
#31 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Stancl\Tenancy\Commands\Seed->handle()
#32 /var/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#33 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#34 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#35 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(663): Illuminate\Container\BoundMethod::call()
#36 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call()
#37 /var/www/vendor/symfony/console/Command/Command.php(291): Illuminate\Console\Command->execute()
#38 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(152): Symfony\Component\Console\Command\Command->run()
#39 /var/www/vendor/symfony/console/Application.php(1014): Illuminate\Console\Command->run()
#40 /var/www/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#41 /var/www/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#42 /var/www/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\Component\Console\Application->run()
#43 /var/www/vendor/laravel/framework/src/Illuminate/Console/Application.php(194): Illuminate\Console\Application->run()
#44 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(336): Illuminate\Console\Application->call()
#45 /var/www/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): Illuminate\Foundation\Console\Kernel->call()
#46 /var/www/vendor/stancl/tenancy/src/Jobs/SeedDatabase.php(35): Illuminate\Support\Facades\Facade::__callStatic()
#47 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Stancl\Tenancy\Jobs\SeedDatabase->handle()
#48 /var/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#49 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#50 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#51 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(663): Illuminate\Container\BoundMethod::call()
#52 /var/www/vendor/stancl/jobpipeline/src/JobPipeline.php(68): Illuminate\Container\Container->call()
#53 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Stancl\JobPipeline\JobPipeline->handle()
#54 /var/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#55 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#56 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#57 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(663): Illuminate\Container\BoundMethod::call()
#58 /var/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call()
#59 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#60 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#61 /var/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()
#62 /var/www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(124): Illuminate\Bus\Dispatcher->dispatchNow()
#63 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
#64 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#65 /var/www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(126): Illuminate\Pipeline\Pipeline->then()
#66 /var/www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#67 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call()
#68 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(425): Illuminate\Queue\Jobs\Job->fire()
#69 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(375): Illuminate\Queue\Worker->process()
#70 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(173): Illuminate\Queue\Worker->runJob()
#71 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(147): Illuminate\Queue\Worker->daemon()
#72 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(130): Illuminate\Queue\Console\WorkCommand->runWorker()
#73 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Queue\Console\WorkCommand->handle()
#74 /var/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#75 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#76 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#77 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(663): Illuminate\Container\BoundMethod::call()
#78 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call()
#79 /var/www/vendor/symfony/console/Command/Command.php(291): Illuminate\Console\Command->execute()
#80 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(152): Symfony\Component\Console\Command\Command->run()
#81 /var/www/vendor/symfony/console/Application.php(1014): Illuminate\Console\Command->run()
#82 /var/www/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#83 /var/www/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#84 /var/www/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\Component\Console\Application->run()
#85 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\Console\Application->run()
#86 /var/www/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#87 {main}
```

**Comment by jonathanpmartins** [comment]
This is an `attempted too many times` error. You should have previous errors that will be more useful to solve your problem.
